#!/bin/sh
set -o errexit

echo
echo '[info] Testing JavaScript'
echo
node js/welcome.js

echo
echo '[info] Building site'
echo
bundle exec jekyll build
echo
echo '[info] Checking links'
echo
linkchecker '_site/index.html'
